[phases.setup]
nixPkgs = ['php81', 'php81Extensions.pdo_mysql', 'composer']
aptPkgs = ['git', 'unzip']

[phases.install]
cmds = ['composer install --no-dev', 'php artisan key:generate']

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT" 

APP_NAME="Sistem Pakar Kandungan"
APP_ENV=production
APP_KEY=base64:your-key
APP_DEBUG=false
APP_URL=https://newsistempakarkandunganbe-production.up.railway.app/
app
DB_CONNECTION=mysql
DB_HOST=${DATABASE_URL}
DB_PORT=3306
DB_DATABASE=railway
DB_USERNAME=root
DB_PASSWORD=${MYSQLPASSWORD}